<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '37366d301fd967b985de68f11d4894da' => $vendorDir . '/php-di/php-di/src/functions.php',
);
