<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitf0a5aec7cdb332c5ea675056d3023319
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('AATXT\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \AATXT\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitf0a5aec7cdb332c5ea675056d3023319', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \AATXT\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitf0a5aec7cdb332c5ea675056d3023319', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\AATXT\Vendor\Composer\Autoload\ComposerStaticInitf0a5aec7cdb332c5ea675056d3023319::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \AATXT\Vendor\Composer\Autoload\ComposerStaticInitf0a5aec7cdb332c5ea675056d3023319::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
